### ISSUE TITLE
item placing problem in WU and 3d mode

### ISSUE THREAD

**Issue by Nytetears** [Warlander/DeedPlanner-3#1]
3.0.2 Alpha standalone version
I am not sure how to explain this but I will give it a try. When I first load the program and map it works wonderfully I can move around and place items fine. After about 20 minutes of placing items on the map, it gets into this mode where I can only place one of an item. For example, I want a bed in each room I place a bed in the room and then go to the 2nd room and place a bed it erases the first bed and places one in the second room.

Also if I place a bed and try to place a chair next to it, it will erase the bed and place the chair. If I save the map and load it I can again place stuff

**Comment by Warlander** [comment]
Issue should be fixed now,
