### ISSUE TITLE
Status question

### ISSUE THREAD

**Issue by graviaDaemon** [Warlander/DeedPlanner-3#21]
Before I start to invest a lot of time usnig this AMAZING deed planner.
Is this still being updated and maintained? 
On steam it says "not yet available", so I downloaded from here, but the last update was in 2020, hence the question

**Comment by Warlander** [comment]
> Is this still being updated and maintained?

In last few years I was mostly doing bugfixes when needed, DeedPlanner isn't going anywhere through - locally downloaded version doesn't need any network connectivity to work and web browser version should always be around too, so there's no need to worry about it being taken away or suddenly stopping working! 🙂 

The project is still active, but there wasn't much development happening in last few years.
