### ISSUE TITLE
Incorrect rotation / missing bridges in WebGL

### ISSUE THREAD

**Issue by PatrickDahlin** [Warlander/DeedPlanner-3#3]
[deed_plan.zip](https://github.com/Warlander/DeedPlanner-3/files/3657015/deed_plan.zip)
When loading this map in both deedplanner 2.9 and 3.0 you can see differences in some object rotations (ovens/arched walls) which are correct in 2.9 but not in 3.0.
Also *all* bridges are missing in 3.0 which are made in 2.9

**Comment by Warlander** [comment]
I made hotfix for the rotation issue of both objects and arched walls, they should load the same way as in DeedPlanner 2 now.

Missing bridges are expected - bridges are not implemented in DeedPlanner 3 yet, so they are ignored when loading the map.
