### ISSUE TITLE
Target Height input field enhancement 

### ISSUE THREAD

**Issue by KSunyo** [Warlander/DeedPlanner-3#42]
Currently, the Target height input field works in the following way: 

https://github.com/Warlander/DeedPlanner-3/assets/18518416/6cc8b346-8f4b-4750-b2ea-efdc33c1f124

As seen in the video, it's easy to get that zero unexpectedly added to your preferred height, causing users possibly applying unwanted heights to tiles.

I propose the following solution to the problem:

https://github.com/Warlander/DeedPlanner-3/assets/18518416/9caf426d-1d0f-44e0-b01b-43e674cb028f

The zero is still the default value for the input field, however, it is now a placeholder text that disappears the moment the user writes a number in the field. This should then also be the inital case for the field, as you can see here: 

![DP_TargetHeight_initial](https://github.com/Warlander/DeedPlanner-3/assets/18518416/99d4fa9e-c9d2-442d-a07e-039907333efb)

**Comment by Warlander** [comment]
Sounds like a very good idea! I will implement this change in a free moment, it shouldn't take long.

**Comment by Warlander** [comment]
Implemented in development version, will be part of 3.2.0 release.

**Comment by KSunyo** [comment]
Wow, you were very fast, I can't wait the update! 💯
