### ISSUE TITLE
Modals move around faster on drag then the mouse

### ISSUE THREAD

**Issue by KSunyo** [Warlander/DeedPlanner-3#43]
When dragging modals, they move somewhat faster than the mouse, therefore making it possible to place them outside the viewport in which case they become inaccessible until reload (as far as I know, although there may be a way to reposition them). 
See video:

https://github.com/Warlander/DeedPlanner-3/assets/18518416/618ec310-8f19-4e52-a06f-b1576f8b918b

**Comment by Warlander** [comment]
Already fixed in current dev version.

**Comment by Warlander** [comment]
There was also issue with window titles being flickery when moved around, this is fixed as well.

**Comment by KSunyo** [comment]
Oh great!
